apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-ml-api
  namespace: housing-namespace
  labels:
    app: housing-ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing-ml-api
  template:
    metadata:
      labels:
        app: housing-ml-api
    spec:
      containers:
        - name: housing-ml-api
          image: lookatravi/housing-ml-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          env:
            - name: MODEL_PATH
              value: "/opt/housing-ml-api/mlruns/292163823275666302/models/m-f4c983a17b8244799713aa308b8101aa/artifacts"
