apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: housing-ml-api-ingress
  namespace: housing-namespace
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: <YOUR-DOMAIN-OR-ELB-DNS>
      http:
        paths:
          - path: /predict
            pathType: Prefix
            backend:
              service:
                name: housing-ml-api
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: housing-ml-api
                port:
                  number: 80
